### ISSUE TITLE
Autogenerate docs with Sphinx and host on readthedocs.org

### ISSUE THREAD

**Issue by anotherjoshsmith** [UWPRG/plumitas#6]
Hosting this appropriately on readthedocs.org (RTD) build will require (I think?) some fiddling with the conf.py and maybe some other files in the doc/ directory. We need to get this working so that maintaining the docs will be manageable as methods are added.

**Comment by wesleybeckner** [comment]
On it!

**Comment by wesleybeckner** [comment]
added to RTD this morning with autodocs generated files

**Comment by anotherjoshsmith** [comment]
Thanks @wesleybeckner! Docs updated in #8.
